FLAGS = {'Austria':     '🇦🇹',
        'Australia':    '🇦🇺',
        'Canada':       '🇨🇦',
        'Germany':      '🇩🇪',
        'Finland':      '🇫🇮',
        'France':       '🇫🇷',
        'Ireland':      '🇮🇪',
        'Italy':        '🇮🇹', 
        'Japan':        '🇯🇵', 
        'Malaysia':     '🇲🇾',
        'Netherlands':  '🇳🇱',
        'Norway':       '🇳🇴',
        'New Zealand':  '🇳🇿',
        'Poland':       '🇵🇱',
        'Russia':       '🇷🇺',
        'Sweden':       '🇸🇪',
        'Singapore':    '🇸🇬',
        'UK':           '🇬🇧', 
        'USA':          '🇺🇸',
        'South Africa': '🇮🇹', 
}
