FLAGS = {
        'Australia':    '🇦🇺',
        'Austria':      '🇦🇹',
        'Canada':       '🇨🇦',
        'Denmark':      '🇩🇰',
        'Eswatini':     '🇸🇿',
        'Finland':      '🇫🇮',
        'France':       '🇫🇷',
        'Germany':      '🇩🇪',
        'Ireland':      '🇮🇪',
        'Italy':        '🇮🇹', 
        'Japan':        '🇯🇵', 
        'Malaysia':     '🇲🇾',
        'Namibia':      '🇳🇦',
        'Netherlands':  '🇳🇱',
        'New Zealand':  '🇳🇿',
        'Norway':       '🇳🇴',
        'Poland':       '🇵🇱',
        'Russia':       '🇷🇺',
        'Sweden':       '🇸🇪',
        'Singapore':    '🇸🇬',
        'South Africa': '🇿🇦', 
        'UK':           '🇬🇧', 
        'USA':          '🇺🇸',
        'England, UK':  '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
        'Scotland, UK': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        'Wales, UK':    '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
        'Northern Ireland, UK': 'NI',
        'St Brelade, Jersey': '🇯🇪',
        'Vale, Guernsey': '🇬🇬',
        'Douglas, Isle of Man': '🇮🇲' 
}
